### ISSUE TITLE
Feature: Server-side

### ISSUE THREAD

**Issue by sternschnaube** [Crystal-Nest/soul-fire-d#36] opened 2023-12-31 07:38 UTC
Could this mod please be designed to work server-side? Allowing vanilla clients to connect to the server.

I see no problem to display players without the mod just the normal fire animation.

**Comment by Crystal-Spider** [comment] 2023-12-31 07:41
It's something I'd actually like to do, but I don't know if it's entirely possible.  
I'll see what I can do.

**Comment by venaminecraft** [comment] 2023-12-31 07:45
Thanks for the fast response.
Sounds great 😊

**Comment by Crystal-Spider** [comment] 2023-12-31 08:05
So, the thing is that there are some core features of this mod that make a server-side only version quite difficult to make.

For starters, there are enchantments. Both client and server need to be aware of enchantments, otherwise it will cause mismatch in the registries.  
Secondly, there is the fact that Soul Fire deals greater damage and having no indicator of that is not good.  
Third, as this mod is an API too, other fires might be registered and the same 2 considerations apply for them too.  

It might actually be easier to make a client-side only version of this mod rather than a server-side only, but even then some core feature would just be disabled and only the visual effect would be left, but there's already a Fabric mod that makes the effect visual only, so I'd see no point in making myself a client-side only version.

I don't think there's much I can do to make it server-side only, but I'll still take some time to see if I can find any solution or workaround.

**Comment by venaminecraft** [comment] 2023-12-31 08:16
Just add a config option to disable the enchantments . Solves the first issue. And it should be in the player hands, if he wants to play with additional enchantments. Myself, I'm not a fan of that.

Set the greater damage to the standart value or keep it higher, which is great. There's no need for an indicator, that's again in the hand of the player who installs this mod. Again, a config option solves this - or even enhance the mod, because you could define higher values.

I'm not aware of a visual mod of it - which is great. I use Torchhit and it adds support for your mod, why I would like to have this mod. I was also not aware of additional enchantments coming with it 😅 

Visual aspects and that it deals higher damage is what I would like to have.

**Comment by Crystal-Spider** [comment] 2023-12-31 08:54
There is already a config option to disable enchantments.  
However, due to how Minecraft work, disabling enchantments means that they still exist, they just can't be obtained in survival.  
So when the mod is server side the issue is still there, because there would be enchantments on the server that don't exist on the client. This being said, I still think it's possible to find a workaround for this problem.

There is no config option for the damage because that's how it should be, Soul Fire deals double the normal fire damage. It's already in Vanilla and, for balancing and consistency reasons, it should remain like that.  
A visual indicator for when something different happens is needed in a game. So I'd need to find some way to make a player understand what's happening, because not only you take more damage when standing in Soul Fire, but you also take more damage if you're burning from Soul Fire. This means that there could easily be a situation where a player is on fire, outside of any fire source, with the Vanilla fire overlay, and yet is taking more damage then usual. This is confusing for a player and I can't allow it to happen.  
So, to solve this, I need to find a way for a player to understand what's happening. And, of course, this solution would need to be server-side only.

The visual only mod is actually both server and client too, I didn't remember well apparently. Indeed server-side logic is most likely needed to keep track of which entity is burning from which kind of fire.

Torch Hit has support for Soul Fire'd because, when Soul Fire'd is installed, not only entities burn from Soul Fire, they also take more damage and all the other things with Soul Fire (es. zombies can attack with Soul Fire too, etc.).

This being said, when trying to make a sever-side only version I need to workaround the enchantments registering and still show some kind of indicator, be it visual or not, for the different fire effect. Especially when considering that with this mod an API comes too that allows other mods or datapack authors to add behavior for different fires, so everything needs to work.

**Comment by venaminecraft** [comment] 2023-12-31 10:15
Thanks for the detailed answer.

In the end it's your design decision about the damage value and it has to be respected 😊

I'm looking forward to your solution.

**Comment by Crystal-Spider** [comment] 2024-04-30 20:20
Waiting for #42

**Comment by Crystal-Spider** [comment] 2024-06-04 13:44
I'm sorry, but I took quite some time and I couldn't find any satisfying server-side only solution, so I'm closing this issue for good.

**Closed as not planned by Crystal-Spider** 2024-06-04 13:44 UTC
Labels: wontfix
