### ISSUE TITLE
Soul Flame on crossbows

### ISSUE THREAD

**Issue by Vic-PT** [Crystal-Nest/soul-fire-d#38] opened 2024-02-13 13:10 UTC
Soul flame, acts like regular flame on crossbows.

Would realy like it if the soul flame enchantment worked correctly on crossbows, making the flame blue and causing soul burning. I'm not asking for soul flame to be compatible with crossbows, I already have a mod for that.

I'm using universal enchants to get the soulflame enchantment on the crossbow.

**Comment by Crystal-Spider** [comment] 2024-02-13 14:16
I understand, I also know what the problem is.  
Unfortunately, blame Mojang for this, Flame injects its code directly into the Bow item rather than the Flame enchantment itself (unlike Fire Aspect where the effect is handled by the enchantment).  
This means that to make Soul Flame apply to bows I had to change the Bow code.  
I'll check how Universal Enchants applies flame to crossbows and I'll see if it's something that should be fixed on my end or on their end.

**Comment by Crystal-Spider** [comment] 2024-02-16 15:51
Speaking with Universal Enchants author, it's currently not possible to make Soul Flame compatible.  
However, he said he will update his mod to allow this, and then I'll have to update mine too.  
Until then, this issue can't be solved.

**Comment by Crystal-Spider** [comment] 2024-06-05 11:19
Update: Universal Enchants author told me that its change is ready but not released yet, and that he will notify me when it'll be available.

**Comment by Crystal-Spider** [comment] 2024-08-07 09:11
From 1.21 this can be done with datapacks.

**Closed as completed by Crystal-Spider** 2024-08-07 09:11 UTC
Labels: other mod, compatibility
