### ISSUE TITLE
Visual bugs with Entity [1.20.2]

### ISSUE THREAD

**Issue by SoulxluoS** [Crystal-Nest/soul-fire-d#35] opened 2023-12-18 14:40 UTC
**Describe the bug**
- Items are not render in the Item Frame
- Entities have a default texture instead of a variant texture
- Entities do not have a baby model

**To Reproduce**
1. Launch world
2. Look at the entities

**Expected behavior**
- Normal visual

**Screenshots**
![2023-12-18_19 29 28](https://github.com/Nyphet/soul-fire-d/assets/70120313/5b6918c7-5195-4584-add4-751df0aedebf)
ain(Main.java:253) ~[1.20.2-0.15.2.jar:?]

**System information:**
 - Minecraft version: 1.20.2 Fabric [Loader 0.15.2]
 - Mod version: 
  [soulfired-1.20.2-3.2.1.0-fabric]
  [ForgeConfigAPIPort-v9.1.2-1.20.2-Fabric]
  [fabric-api-0.91.2+1.20.2]
 
**Additional context**
[19:39:10] [Render thread/ERROR]:
 Error executing task on Client
java.lang.IllegalStateException: Invalid entity data item type for field 17 on entity class_1472['����'/119389, l='ClientLevel', x=1272.45, y=85.00, z=1160.55]: old=false(class java.lang.Boolean), new=17(class java.lang.Byte)
	at net.minecraft.class_2945.method_12785(class_2945.java:204) ~[client-intermediary.jar:?]
	at net.minecraft.class_2945.method_12779(class_2945.java:191) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11093(class_634.java:516) ~[client-intermediary.jar:?]
	at net.minecraft.class_2739.method_11808(class_2739.java:46) ~[client-intermediary.jar:?]
	at net.minecraft.class_2739.method_11054(class_2739.java:10) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1231) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:856) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:253) ~[1.20.2-0.15.2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.2.jar:?]

**Comment by Crystal-Spider** [comment] 2023-12-18 15:21
Do you have the mod installed on both server and client?

**Comment by SoulxluoS** [comment] 2023-12-18 16:48
Only client. 
Playing on Paper Server

**Comment by Crystal-Spider** [comment] 2023-12-18 17:18
Duplicate of #8 

This mod is required on **both** server **and** client, it won't work otherwise.  
It's explicitly stated on the mod page and there have been several other issues with the same problem.  
Please make sure you have read carefully the mod requirements, infos, and other issues.

**Closed as completed by Crystal-Spider** 2023-12-18 17:18 UTC
Labels: duplicate
